//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManagementSystem.Entities.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exception
    {
        public int Id { get; set; }
        public string actionPerformed { get; set; }
        public string exceptionCaught { get; set; }
        public string exceptionMessage { get; set; }
        public Nullable<System.DateTime> dateRecorded { get; set; }
    }
}
